Blog/urls.py
from django.urls import path, include
from .views import *
from . import views

urlpatterns = [
    
    path('home/', views.blogHome, name='blogHome'),
    path('blog-detail/<slug>' , blog_detail , name="blog_detail"),
    

]

Store/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from . import views

from .views import *
from .views import Cart, Checkout, OrderView, ViewFarmer
from .middlewares.auth import auth_middleware
from django.contrib.auth import views as auth_views
urlpatterns = [
    
   
    path('', views.index, name='home'),
    path('customer_reg', views.customer_reg, name="cus_reg"),
    path('farmer_registration', views.farmer_reg, name = 'fa_reg'),
    path('officer_registration', views.agri_officer_reg, name = 'agri_officer_reg'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/', auth_middleware(views.profile_view), name='profile'),
    path('edit_profile/',views.edit_profile, name='edit_profile_info'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('viewPro/<int:pk>', ViewProduct.as_view(), name='productDetails'),
    path('viewFar/<int:pk>', ViewFarmer.as_view(), name='farmerDetails'),

    path('check-out',auth_middleware(Checkout.as_view()), name='checkout'),
    
    path('return_login/', views.return_login, name='return_login'),
    path('typeSign', views.typesSign, name='type_Sign'),
    path('order/', auth_middleware(OrderView.as_view()), name='order_page'),
    path('invoice/', auth_middleware(InvoiceView.as_view(),), name='invoice_page'),
    
    #path('password/', auth_views.PasswordChangeView.as_view(template_name= 'profile/changePass.html') )
    path('password/', PasswordsChangeView.as_view(template_name= 'profile/changePass.html') ),
    path('password_success/', views.password_success, name="password_success"),
    #path('edit_profile/', UserEditView.as_view(), name= "edit_profiles"),
    
    #path('farmer_reg/', views.farmer_reg)
]

WeatherApp/urls.py
from django.urls import path
from .views import *
app_name = 'WeatherApp'
urlpatterns =[
    
    path('', CityWeatherView, name='city_weather'),
    path('remove/<city_name>/', City_delete, name='city_remove'),
    ]

farmersAid/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('Store.urls')),
    path('blog/', include('Blog2.urls')),
    #path('weather_app/', include('weather.urls')),
    #path('weather_app/delete/<int:id>', include('weather.urls')),
    path('weather_app/', include('WeatherApp.urls', namespace='WeatherApp')),
    path('froala_editor/',include('froala_editor.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/models/categories.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)

    @staticmethod
    def get_all_category():
        return Category.objects.all()

    def __str__(self):
        return self.name

Store/models/extra.py
# user_type= models.CharField(max_length=30, choices=USER_CHOICES, default='Customer')

# USER_CHOICES =(
#     ("Customer", "Customer"),
#     ("Farmer", "Farmer"),
   
# )

Store/models/orders.py
from Store.models.unit_type import Unit_Type
from Store.models.products import Product
from django.db import models
from .products import Product
from django.contrib.auth.models import User
import datetime


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.TextField(max_length=300, blank=True, default='')
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
    unit = models.ForeignKey(Unit_Type, on_delete=models.CASCADE, default='kg')
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length = 254)
    date = models.DateField(default = datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def __str__(self):
        return self.product.name

    @staticmethod
    def get_orders_by_user(user_id):
        return Order\
        .objects\
        .filter(user = user_id).order_by('-date')

Store/models/products.py
from Store.models.userprofile import UserProfile
from django.db import models
from .categories import Category
from .unit_type import Unit_Type
from django.contrib.auth.models import User
from django.utils.html import format_html

class Product(models.Model):
    
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,  default=1)
    unit= models.ForeignKey(Unit_Type, on_delete=models.CASCADE,  default='kg')
    Unit_price = models.IntegerField(default=0)

    #k_name = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    quantity = models.IntegerField(default=0)
    description = models.CharField(max_length=200, default='', null=True, blank=True)
    image = models.ImageField(upload_to = 'upload/productsImg/')
    krishok = models.ForeignKey(User, limit_choices_to= { 'groups__name': 'Farmer'}, on_delete=models.CASCADE, default=1)

    def image_tag(self):
        return format_html(
            '<img src="/abcd/show/{}" style=" width:40px; height:40px; border-radius:50% "/>'.format(self.image)
        )
   
    @staticmethod
    def get_all_products():
        return Product.objects.all()

    #Filtering by Category Id: 
    # this method will bring all products by its categoryID
    @staticmethod
    def get_all_products_by_id(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        else:
            return Product.get_all_products()

    
    @staticmethod
    def get_product_by_ids(ids):
        return Product.objects.filter(id__in= ids)

    

Store/models/unit_type.py
from django.db import models

class Unit_Type(models.Model):
    unit_name = models.CharField(max_length=50)

    def __str__(self):
        return self.unit_name

Store/forms.py
# from django import forms
# from django.contrib.auth.models import User, Group
# from django.contrib.auth.forms import UserCreationForm
# from .models.userprofile import UserProfile
# from django.forms import ModelForm

# class CustomerRegisterForm(UserCreationForm):
#     email = forms.EmailField()

#     class Meta:
#         model = User
   
#         #group = Group(name='Farmer')
#         fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

# class UserProfileForm(ModelForm):
#     class Meta:
#         model = UserProfile
   
#         #group = Group(name='Farmer')
#         fields = '__all__'

Store/views.py
from django.views import generic
from Store.templatetags.cart import total_price
from Store.models.unit_type import Unit_Type
from django.db.models.query import EmptyQuerySet, QuerySet
from Store.models.categories import Category
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect, HttpResponseRedirect
from .models.userprofile import UserProfile
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, UserChangeForm
#for email
from django.conf import settings
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string
from .models.products import Product
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import View, DetailView
from .models.products import Product
from .models.orders import Order
from Store.middlewares.auth import auth_middleware
from django.conf import settings
from django.core.mail import send_mail
from .templatetags.cart import *
from .templatetags.custom_filter import *
from django.contrib import messages
from .forms2 import *
from django.urls import reverse_lazy
from django.core.mail import EmailMessage, EmailMultiAlternatives
# from django.utils.decorators import method_decorator
#-----home------
# class Index(View):

    # def post(self, request):
    #     product_id=request.POST.get('product_id')
    #     print("product ID: ",product_id)
    #     return redirect('home')

    # def get(self, request):
    #     products = None
    #     categories = Category.get_all_category()
    
    #     categoryID = request.GET.get('category_id')

    #     if categoryID:
    #         products = Product.get_all_products_by_id(categoryID)
    #     if not products:
    #         print("No item")
    #         messages.error(request, "Opps! No products are available on this category")
    #     else:
    #       products = Product.get_all_products()

    # #--paginator
    #     paginator = Paginator(products, 6)
    #     page_number = request.GET.get('page')
    #     products = paginator.get_page(page_number)


    #     data = {}
    #     data['products'] = products
    #     data['categories']= categories
    #     #return render(request, 'order.html')
    #     print('you are: ',request.session.get('current_username'))
    #     return render(request, 'store/index.html', data)

#@login_required(login_url='/login/')
#--------Index---Home--------
def index1(request):
    return render(request, 'store/index.html')

def index(request):
    #Before serving index page clearing cart dict obj.
    cart = request.session.get('cart')
    if not cart:
        request.session["cart"]= {}

    products = None
    categories = Category.get_all_category()
    
    categoryID = request.GET.get('category_id')

    if categoryID:
        products = Product.get_all_products_by_id(categoryID)
        if not products:
            print("No item")
            messages.error(request, "Opps! No products are available on this category")
    else:
        products = Product.get_all_products()
    
    if request.method == 'POST':
        product=request.POST.get('product')
        remove = request.POST.get('remove')
        #cart access in session as a cart object
        #jodi prothom theke cart na thake tobe cart object create korle ki hbe?
        cart = request.session.get('cart')# first this return None
        #Now I will check availability of cart from before or not:
        #how to logic it: using if conditions:
        if cart:
            quantity = cart.get(product)
            if quantity:
                
                if remove:
                    if quantity <=1:
                        cart.pop(product)
                    else:
                        cart[product] = quantity-1
                        
                else:
                    cart[product] = quantity+1
            else:
                cart[product] = 1
        else:
            cart= {} #assigning empty object here
            cart[product] = 1 # 1 product add to cart

        request.session['cart'] = cart
        # print("cart:--->",request.session['cart'])

        # print("product ID: ",product)
        return redirect('home')
        

    # #--paginator
    # paginator = Paginator(products, 6)
    # page_number = request.GET.get('page')
    # products = paginator.get_page(page_number)


    data = {}
    data['products'] = products
    data['categories']= categories
    #return render(request, 'order.html')
    #current_user_name = request.session.get('current_username')
    # request.session.get('')
    return render(request, 'store/index.html', data)


#------------login------------
def loginPage(request, template_name='account/login.html'):
    return_url = None
    if request.method == 'GET':
        return_url = request.GET.get('return_url')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

            # print("the user is : ---> ",user.id)
            
            request.session['current_user_id'] = user.id
            request.session['current_username'] = user.username
            request.session['full_name'] = user.first_name
            request.session['last_name'] = user.last_name


            if return_url:
                return HttpResponseRedirect(return_url)
            else:
                return_url = None
                return redirect('home')
        else:
            messages.error(request, 'Username or password is incorrect')

    context = {}
    return render(request, template_name, context)

#-------Logout--------

def logoutUser(request):
    #logout(request)
    request.session.clear()
    cart = request.session.get('cart')
    if not cart:
        request.session["cart"]= {}
    return redirect('login')

#--------Sign up type---------

def typesSign(request):   
    return render(request, 'account/typeSign.html')

#---------customer registration-----
def customer_reg(request):
    form = CustomerRegForm()
    if request.method == 'POST':
        form = CustomerRegForm(request.POST)
        if form.is_valid():
            #CustomerRegForm.is_Exist_email()
            user = form.save()
            user.save()
            group = Group.objects.get(name='Customer')
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account created successfully for '+ username ) 

            return redirect('login')

    context = {'form': form}
    return render(request, 'account/cus_reg.html', context)

#---farmer registration------
def farmer_reg(request):
    
    profile_form = FarmerRegistrationForm(request.POST)
    Info_Profile_form = InfoUserProfileForm(request.POST)
    if request.method == 'POST':
        
        profile_form = FarmerRegistrationForm(request.POST)
        Info_Profile_form = InfoUserProfileForm(request.POST, request.FILES)
        
        #validation
        #phone = Info_Profile_form.cleaned_data.get('phone')
        # postData = request.POST
        # phone = postData.get('phone')
        # if len(phone) < 11 :
        #     messages.error(request, 'Phone length must be in 11 char long')
        #     return redirect(request, 'account/krishok_reg.html')
        # elif not type(phone) == int:
        #     messages.error(request, 'Character not allowed in phone no.')
        #     return redirect(request, 'account/krishok_reg.html')
        


        if profile_form.is_valid() and Info_Profile_form.is_valid():
            # print(Info_Profile_form.cleaned_data)
            user = profile_form.save()
            print("this is user: ",user)
            user.save()
            group = Group.objects.get(name='Farmer')
            user.groups.add(group)

            # profile = Info_Profile_form.save(commit=False)
            profile = user.userprofile
            profile.address = Info_Profile_form.cleaned_data.get('address', None)
            profile.national_id_no = Info_Profile_form.cleaned_data.get('national_id_no', None)
            profile.phone = Info_Profile_form.cleaned_data.get('phone', None)
            #profile.user = user
            
            if request.FILES:
                print('Yes')
                img = request.FILES['image']
                profile.image.save(img.name, img, save=True)
                nimg = request.FILES['national_id']
                profile.national_id.save(nimg.name, nimg, save=True)

            profile.save()

            username = profile_form.cleaned_data.get('username')
            messages.success(request, 'Account created successfully for '+ username ) 
            return redirect('login')
        
    context = {
        'profile_form':profile_form, 
        'Info_Profile_form':Info_Profile_form
        }
    return render(request, 'account/krishok_reg.html', context)        

#Agriculture_officer
def agri_officer_reg(request):
    
    profile_form = FarmerRegistrationForm(request.POST)
    Info_Profile_form = InfoUserProfileForm(request.POST)
    if request.method == 'POST':
        
        profile_form = FarmerRegistrationForm(request.POST)
        Info_Profile_form = InfoUserProfileForm(request.POST, request.FILES)
        print(request.FILES)
        


        if profile_form.is_valid() and Info_Profile_form.is_valid():
            print(Info_Profile_form.cleaned_data)
            user = profile_form.save()
            print("this is user: ",user)
            user.save()
            group = Group.objects.get(name='Agri_officer')
            user.groups.add(group)

Store/templates/store/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load cart %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--new entry-->
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <!-- Bootstrap CSS -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!--<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    {% block weather_css %}
        
    {% endblock %}

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    <title>farmerShop(digital solution for farmer)</title>
    <style>

    body{
      
      /* background-image:url('{{ STATIC_URL }}picture/krishok.png'); */
      /* background-image:url('{% static "picture/krishok.png" %}');  */
      background: rgba(47, 57, 49, 0.3) ;
      /* Green background with 30% opacity */
      /* background-repeat:no-repeat; */
      /* background-size:1380px 900px; */
      /* background-image: url('{% static "picture/krishok.png"%}');  */
    }


    /*Csss*/
 @media screen and (min-width: 980px){
    .nav-item:hover{
        
        background:rgb(32, 23, 23);
        transition: all 400ms ease-in-out;
    }
}

@media screen and(min-width: 400px){
    .dropdown-item a{
        margin-left: 4rem;

    }
    .drop:hover{
        
        background:rgb(53, 28, 28);
        transition: all 400ms ease-in-out;
    }

   

    
} 
/* .drop-item:hover{
        
        background:rgb(53, 28, 28);
        transition: all 400ms ease-in-out;
    } */

    .dropdown-item:hover{
        background-color: rgb(18, 10, 10);
    }

    .nav-item:hover{
        background-color: rgb(18, 10, 10);
    }
    </style>
</head>

<body>
<!--new div-->

<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light "
     style="background-color: rgb(212, 230, 215); color:rgb(245, 245, 237); ">


    <div class="container-fluid" style="background:rgb(7, 3, 49); ">
        <a class="navbar-brand text-light" href="/">farmerShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent"
             style="background:rgb(46, 13, 113);  position: relative;z-index: 1000;">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="color:white;">

                <li class="nav-item" >
                    
                    <a class="nav-link active text-light" aria-current="page" href="/">
                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-shop float-right text-light"></i></span>
                        Shop
                    </a>
                </li>
                <!-- <li class="nav-item" >
                    
                    <a class="nav-link active text-light" aria-current="page" href="#love">
                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-solid fa-bag-shopping text-light"></i></span>

                        
                        Shop
                    </a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link active text-light" aria-current="page" href="{% url 'home_Blog' %}">
                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-hand-holding-hand float-right text-light"></i></span>

                        
                        Blog
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active text-light" aria-current="page"
                       href="{% url 'WeatherApp:city_weather' %}">
                       <span><i class="fa-2x p-2 mt-3 fa-solid fa-cloud float-right text-light"></i></span>

                      
                       Weather
                    </a>
                </li>


            </ul>

            {% if request.user.is_authenticated %}

            <div class=" lead d-flex mt-2 text-light">
                
                Welcome:<span></span>
                &nbsp;
                {{request.user.get_full_name}} &nbsp; ||
            </div>

            {% endif %}


            <ul class="navbar-nav my-2 my-lg-0">

                <li class="nav-item">
                    <a class="nav-link active text-light" aria-current="page" href="{% url 'cart' %}">
                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-cart-plus float-right text-light"></i>
                                
                        </span>
                        
                        Cart
                        <span class="badge bg-info">{{request.session.cart.keys|length}}
                            

                        </span>
                    </a>
                </li>
                {% if not request.session.current_user_id %}

                  <!--subnavitem-->
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">

                       <span><i class="fa-2x p-2 mt-3 fa-solid fa-user-plus float-right text-light"></i>
                       
                        SignUp
                    </a>
                    <ul class="dropdown-menu resdrop"  style="margin-left: -3.65rem; background:rgb(41, 132, 217);">
                        <li class="drop">
                            <a class="dropdown-item " 
                            style=" display: inline-block;  color: #fff" href="{% url 'cus_reg' %}">
                                Register As Customer
                            </a>
                        </li>

                        <li class="drop">
                            <a class="dropdown-item text-white" href="{% url 'fa_reg' %}" >Register As Farmer</a>
                        </li>

                        <li class="drop d-flex"><a class="dropdown-item text-white" href="{% url 'agri_officer_reg' %}">Register As Agri_Officer</a></li>
                    </ul>
                </li>
                <!--subnavitem-->

                <li class="nav-item">
                    <a class="nav-link active text-light" aria-current="page" href="{% url 'login' %}">
                        
                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-right-to-bracket float-right text-light"></i>
                        
                        Login</a>
                </li>

              
                {% else %}

                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'profile' %}">
                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-user float-right text-light"></i> 
                        
                        Profile</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active text-light" aria-current="page" href="{% url 'order_page' %}">

                        <span><i class="fa-2x p-2 mt-3 fa-solid fa-arrow-down-a-z float-right text-light"></i>
                        
                        Order</a>
                </li>


                <li class="nav-item">
                    
                    <a class="nav-link text-light" href="{% url 'logout' %}">

                    <span><i class="fa-2x p-2 mt-3 fa-solid fa-right-from-bracket float-right text-light"></i>
                        
                        Logout
                    </a>
                </li>


                {% endif %}

            </ul>


        </div>
    </div>
</nav>
<!--CLOSE nAV-->

<!--Block here-->
{% block content %}


{% endblock %}
<!--close block-->

   <!--fOOTER-->

{% include 'store/footer.html' %}
          
   
   <!--fOOTER-->


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous">
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous">
</script>


<script>
      M.AutoInit();
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<!--<script src="{% static 'js/owl.carousel.min.js'%}"></script>-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
        integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
</script>


<script>
      $(document).ready(function(){
    $(".owl-carousel").owlCarousel(
    {
      loop: true,
  
        autoplay: true,
  
        nav: false,
        responsiveClass: true,
      responsive:{
          0:{
              items:1,
              nav:true
          },
          600:{
              items:3,
              nav:false
          },
          1000:{
              items:3,
              nav:true,
              loop:false
          }
      }
  
    }
    );
  });
  
  

      $(document).ready(function(){
        $(".owl-carousel").owlCarousel();
      });







</script>

</body>
</html>

Store/templates/store/boot.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

Store/templates/store/email_template.html
<h1>Hey {{first_name}} {{last_name}}!!</h1>

<h3>Your User Name: {{username}} </h3>

<h4>We just want to thank you for purchasing products from us.</h4>

<h2 style="display: inline-block; color:rgb(25, 25, 55); text-align:center;">Your Order details: </h2>

<h3>Total Order's Amount:---> <mark>{{curr}}</mark></h3>

<table style="border: 1px solid rgb(14, 13, 13);">
    <thead>
        <tr style="color:darkblue; font-weight:bold ; ">
            <th >Order Total</th>
            <th>Shipping Address </th>
            <th>Your Phone No</th>
            <th>Order Date</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>&nbsp;{{curr}}</td>
            <td>&nbsp;{{address}} &nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>&nbsp;{{phone}} </td>
            <td>&nbsp;{{date}}</td>

        </tr>
    </tbody>
</table>

<br>

<h4>
    You have ordered total <mark>{{curr}}</mark> form us. You will get your desired products within <mark><b>3</b></mark> days at your given address( <b>{{address}}</b>) and our service stuff will contact with you at <mark>{{phone}}</mark>.
</h4> 

<h3 style="color:rgb(44, 4, 78);">
    Thank you so much for being with us. Looking forward to seeing you there):
</h3> 

<!-- <a href="{% url 'invoice_page' %}" style="text-decoration: none; padding: 20px; background-color:black; color:white;">Generate Invoice</a> -->


<h3 style="font-size:20px">
From,
<br>
FarmerShop company LTD.
</h3>